version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jsyslogd
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    build: .
    ports:
      - "3000:3000"
      - "514:514"
      - "514:514/udp"
    depends_on:
      - db
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: jsyslogd
      PGHOST: db
      PGPORT: 5432
volumes:
  db-data:
